### ISSUE TITLE
Menu labels are wrong with the Vector skin

### ISSUE THREAD

**Issue by Seudo3** [he7d3r/mw-gadget-LanguageConverter#1]
Hello,
When using the gadget at the French Wikisource (and probably on other Wikisources), the four menu entries have all the same label after converting the language.
For example:

- on the French Wikisource, enable the gadget "_Active les options de modernisation du texte pour les textes qu’il est possible de moderniser_" (or load https://fr.wikisource.org/wiki/MediaWiki:Gadget-modernisation.js in your `common.js`)
- open https://fr.wikisource.org/w/index.php?title=Fables_de_La_Fontaine_(%C3%A9d._Barbin)/1/Le_Renard_et_les_Raisins&variant=fr&useskin=vector
- click on "_Orthographe moderne_"
- then the four entries are labelled "_Orthographe moderne_".

If I'm correct, the bug is at line 582 in `LanguageConverter.js` : the selector should be `$( '#p-cactions-label' )` (which only includes the menu title), not `$( '#p-variants-js' )` (which also includes the entries inside the menu).

This bug appears in Vector 2010 and Vector 2020, not in Monobook (because Monobook does not use spans here, so this line produces no effect).

**Comment by he7d3r** [comment]
Fixed by https://github.com/he7d3r/mw-gadget-LanguageConverter/commit/61b312d972db4086d837514802e0c309275425c0. Thank you for reporting!
